name: Quality_Assessment_&_Awarding_v2

on:
  push:
    branches:
      - '**'
    
    
jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: SQAaaS assessment with unit testing (QC.Uni) step
        uses: eosc-synergy/sqaaas-assessment-action@v2
          
    
